VARIABLE LABELS
AGE "Please type in your age. 请输入您的年龄"
Q0_1 "First of all, we would like to know your leisure time activities. Have you ever been to below places? (MA)首先我们想了解一下您的休闲娱乐情况。请问您休闲时间是否曾经去过以下场所？（复选）"
Q0_2 "First of all, we would like to know your leisure time activities. Have you ever been to below places? (MA)首先我们想了解一下您的休闲娱乐情况。请问您休闲时间是否曾经去过以下场所？（复选）"
Q0_3 "First of all, we would like to know your leisure time activities. Have you ever been to below places? (MA)首先我们想了解一下您的休闲娱乐情况。请问您休闲时间是否曾经去过以下场所？（复选）"
Q0_4 "First of all, we would like to know your leisure time activities. Have you ever been to below places? (MA)首先我们想了解一下您的休闲娱乐情况。请问您休闲时间是否曾经去过以下场所？（复选）"
Q0_5 "First of all, we would like to know your leisure time activities. Have you ever been to below places? (MA)首先我们想了解一下您的休闲娱乐情况。请问您休闲时间是否曾经去过以下场所？（复选）"
Q0_6 "First of all, we would like to know your leisure time activities. Have you ever been to below places? (MA)首先我们想了解一下您的休闲娱乐情况。请问您休闲时间是否曾经去过以下场所？（复选）"
Q0_7 "First of all, we would like to know your leisure time activities. Have you ever been to below places? (MA)首先我们想了解一下您的休闲娱乐情况。请问您休闲时间是否曾经去过以下场所？（复选）"
Q0_8 "First of all, we would like to know your leisure time activities. Have you ever been to below places? (MA)首先我们想了解一下您的休闲娱乐情况。请问您休闲时间是否曾经去过以下场所？（复选）"
Q0_9 "First of all, we would like to know your leisure time activities. Have you ever been to below places? (MA)首先我们想了解一下您的休闲娱乐情况。请问您休闲时间是否曾经去过以下场所？（复选）"
Q0_10 "First of all, we would like to know your leisure time activities. Have you ever been to below places? (MA)首先我们想了解一下您的休闲娱乐情况。请问您休闲时间是否曾经去过以下场所？（复选）"
Q0_11 "First of all, we would like to know your leisure time activities. Have you ever been to below places? (MA)首先我们想了解一下您的休闲娱乐情况。请问您休闲时间是否曾经去过以下场所？（复选）"
BE2A01_1 "Please select all the brands of theme park you have ever heard of, even if you’re not very familiar with them. 您曾经听说过以下哪些游乐园/主题乐园呢？请选出所有您知道的品牌，即使您并不熟悉这些品牌也不要紧。"
BE2A01_2 "Please select all the brands of theme park you have ever heard of, even if you’re not very familiar with them. 您曾经听说过以下哪些游乐园/主题乐园呢？请选出所有您知道的品牌，即使您并不熟悉这些品牌也不要紧。"
BE2A01_3 "Please select all the brands of theme park you have ever heard of, even if you’re not very familiar with them. 您曾经听说过以下哪些游乐园/主题乐园呢？请选出所有您知道的品牌，即使您并不熟悉这些品牌也不要紧。"
BE2A01_4 "Please select all the brands of theme park you have ever heard of, even if you’re not very familiar with them. 您曾经听说过以下哪些游乐园/主题乐园呢？请选出所有您知道的品牌，即使您并不熟悉这些品牌也不要紧。"
BE2A01_5 "Please select all the brands of theme park you have ever heard of, even if you’re not very familiar with them. 您曾经听说过以下哪些游乐园/主题乐园呢？请选出所有您知道的品牌，即使您并不熟悉这些品牌也不要紧。"
BE2A01_6 "Please select all the brands of theme park you have ever heard of, even if you’re not very familiar with them. 您曾经听说过以下哪些游乐园/主题乐园呢？请选出所有您知道的品牌，即使您并不熟悉这些品牌也不要紧。"
BE2A01_7 "Please select all the brands of theme park you have ever heard of, even if you’re not very familiar with them. 您曾经听说过以下哪些游乐园/主题乐园呢？请选出所有您知道的品牌，即使您并不熟悉这些品牌也不要紧。"
BE2A02_1 "Please select all the brands of theme park you have ever VISITED. 请问您曾经去过以下哪些国内的游乐园/主题乐园? [可多选] [随机出示]"
BE2A02_2 "Please select all the brands of theme park you have ever VISITED. 请问您曾经去过以下哪些国内的游乐园/主题乐园? [可多选] [随机出示]"
BE2A02_3 "Please select all the brands of theme park you have ever VISITED. 请问您曾经去过以下哪些国内的游乐园/主题乐园? [可多选] [随机出示]"
BE2A02_4 "Please select all the brands of theme park you have ever VISITED. 请问您曾经去过以下哪些国内的游乐园/主题乐园? [可多选] [随机出示]"
BE2A02_5 "Please select all the brands of theme park you have ever VISITED. 请问您曾经去过以下哪些国内的游乐园/主题乐园? [可多选] [随机出示]"
BE2A02_6 "Please select all the brands of theme park you have ever VISITED. 请问您曾经去过以下哪些国内的游乐园/主题乐园? [可多选] [随机出示]"
BE2A02_7 "Please select all the brands of theme park you have ever VISITED. 请问您曾经去过以下哪些国内的游乐园/主题乐园? [可多选] [随机出示]"
BE2A03_1 "Please select all the brands of theme park you ever visited in the P12M. 请选出所有您在过去12个月内去过的游乐园/主题乐园。"
BE2A03_2 "Please select all the brands of theme park you ever visited in the P12M. 请选出所有您在过去12个月内去过的游乐园/主题乐园。"
BE2A03_3 "Please select all the brands of theme park you ever visited in the P12M. 请选出所有您在过去12个月内去过的游乐园/主题乐园。"
BE2A03_4 "Please select all the brands of theme park you ever visited in the P12M. 请选出所有您在过去12个月内去过的游乐园/主题乐园。"
BE2A03_5 "Please select all the brands of theme park you ever visited in the P12M. 请选出所有您在过去12个月内去过的游乐园/主题乐园。"
BE2A03_6 "Please select all the brands of theme park you ever visited in the P12M. 请选出所有您在过去12个月内去过的游乐园/主题乐园。"
BE2A03_7 "Please select all the brands of theme park you ever visited in the P12M. 请选出所有您在过去12个月内去过的游乐园/主题乐园。"
BE3 "How likely are you to visit Shanghai Disney Resort in the next 12 months when you plan to VISIT AN AMUSEMENT PARK/THEME PARK? 当您在未来12个月内计划去游乐园/主题乐园时，您考虑上海迪士尼度假区的可能性是怎样的?"
POP1 "When do you plan to visit SHDR? 您刚刚提到您会去上海迪士尼度假区，请问您计划什么时候去？（单选）"
Q5d_1 "You just said you have been to SHDR, please recall which one of below attractions is your favorite? (2 options)您提到曾经去过上海迪士尼度假区，请问您最喜欢以下哪项设施呢？您可以最多选择2个设施。 (最多选两项)"
Q5d_2 "You just said you have been to SHDR, please recall which one of below attractions is your favorite? (2 options)您提到曾经去过上海迪士尼度假区，请问您最喜欢以下哪项设施呢？您可以最多选择2个设施。 (最多选两项)"
Q5d_3 "You just said you have been to SHDR, please recall which one of below attractions is your favorite? (2 options)您提到曾经去过上海迪士尼度假区，请问您最喜欢以下哪项设施呢？您可以最多选择2个设施。 (最多选两项)"
Q5d_4 "You just said you have been to SHDR, please recall which one of below attractions is your favorite? (2 options)您提到曾经去过上海迪士尼度假区，请问您最喜欢以下哪项设施呢？您可以最多选择2个设施。 (最多选两项)"
Q5d_5 "You just said you have been to SHDR, please recall which one of below attractions is your favorite? (2 options)您提到曾经去过上海迪士尼度假区，请问您最喜欢以下哪项设施呢？您可以最多选择2个设施。 (最多选两项)"
Q5d_6 "You just said you have been to SHDR, please recall which one of below attractions is your favorite? (2 options)您提到曾经去过上海迪士尼度假区，请问您最喜欢以下哪项设施呢？您可以最多选择2个设施。 (最多选两项)"
Q5d_7 "You just said you have been to SHDR, please recall which one of below attractions is your favorite? (2 options)您提到曾经去过上海迪士尼度假区，请问您最喜欢以下哪项设施呢？您可以最多选择2个设施。 (最多选两项)"
Q5d_8 "You just said you have been to SHDR, please recall which one of below attractions is your favorite? (2 options)您提到曾经去过上海迪士尼度假区，请问您最喜欢以下哪项设施呢？您可以最多选择2个设施。 (最多选两项)"
NEWS1_1 "Have you heard of any of below news about SHDR? (MA) 请问您是否在任何地方听说过有关上海迪士尼乐园的以下消息呢？（多选）"
NEWS1_2 "Have you heard of any of below news about SHDR? (MA) 请问您是否在任何地方听说过有关上海迪士尼乐园的以下消息呢？（多选）"
NEWS1_3 "Have you heard of any of below news about SHDR? (MA) 请问您是否在任何地方听说过有关上海迪士尼乐园的以下消息呢？（多选）"
NEWS1_4 "Have you heard of any of below news about SHDR? (MA) 请问您是否在任何地方听说过有关上海迪士尼乐园的以下消息呢？（多选）"
NEWS1_5 "Have you heard of any of below news about SHDR? (MA) 请问您是否在任何地方听说过有关上海迪士尼乐园的以下消息呢？（多选）"
NEWS1_6 "Have you heard of any of below news about SHDR? (MA) 请问您是否在任何地方听说过有关上海迪士尼乐园的以下消息呢？（多选）"
GENDER "Are you…?(OCO) 请问您的性别是…?(单选)"
INCOME "Which of these income bands does your gross monthly household income fit into?  By gross, this means before tax, including bonus, salary and allowance, etc.（OCO） 请问以下哪一个收入段与您家庭的月总收入相符？总收入是指税前收入，包括奖金，工资，津贴等(单选)"
LOCALRES "How long have you lived in this city?（OCO） 请问您在本市连续居住了多长时间？（单选）"
QMSTA "Which of these statements best applies to you now?(OCO) 请问以下哪一项最适合描述您目前的情况呢？(单选)"
.
EXECUTE.



VALUE LABELS
/AGE
 1 "18 to 24 18-24岁"
 2 "25 to 29 25-29岁"
 3 "30 to 34 30-34岁"
 4 "35 to 39 35-39岁"
 5 "40 to 44 40-44岁"
 6 "45 to 50 45-50岁"
/Q0_1 to Q0_11
 1 "Amusement/ Theme park 大型游乐园/主题乐园 "
 2 "Café 咖啡厅"
 3 "Cinema 电影院"
 4 "Theatre 剧院"
 5 "Museum Museum 博物馆/艺术馆"
 6 "KTV KTV KTV场所"
 7 "Gym Gym 健身房"
 8 "Beach 海滩"
 9 "Botanic garden 植物园"
 10 "Aquarium 海洋馆"
 98 "None of above (EXCLUSIVE) 以上均无 （排他）"
/BE2A01_1 to BE2A01_7
 1 "Shanghai Disney Resort 上海迪士尼度假区"
 2 "Happy Valley 欢乐谷"
 3 "Chimelong Resorts 长隆旅游度假区 （广州、珠海）"
 4 "Fantawild Adventure 方特欢乐世界"
 5 "Wanda Theme park  万达主题乐园（南昌、西双版纳、合肥、哈尔滨）"
 6 "Shanghai Haichang Ocean Park 上海海昌海洋公园"
 98 "Never heard of any of these 从来没有听说过以上任何游乐园/主题乐园"
/BE2A02_1 to BE2A02_7
 1 "Shanghai Disney Resort 上海迪士尼度假区"
 2 "Happy Valley 欢乐谷"
 3 "Chimelong Resorts 长隆旅游度假区 （广州、珠海）"
 4 "Fantawild Adventure 方特欢乐世界"
 5 "Wanda Theme park  万达主题乐园（南昌、西双版纳、合肥、哈尔滨）"
 6 "Shanghai Haichang Ocean Park 上海海昌海洋公园"
 98 "Never visited any of these  以上皆无"
/BE2A03_1 to BE2A03_7
 1 "Shanghai Disney Resort 上海迪士尼度假区"
 2 "Happy Valley 欢乐谷"
 3 "Chimelong Resorts 长隆旅游度假区 （广州、珠海）"
 4 "Fantawild Adventure 方特欢乐世界"
 5 "Wanda Theme park  万达主题乐园（南昌、西双版纳、合肥、哈尔滨）"
 6 "Shanghai Haichang Ocean Park 上海海昌海洋公园"
 98 "Never visited any of these in P12M 过去12个月内都没有去过"
/BE3
 1 "I would definitely visit it 我一定会去"
 2 "I am very likely to visit it 我非常有可能去"
 3 "I possibly would visit it 我可能会去"
 4 "I am not very likely to visit it 我可能不会去"
 5 "I would definitely not visit it 我一定不会去"
/POP1
 1 "最近1个月内 Within one month"
 2 "1-3个月内 Between 1-3 months"
 3 "3-6个月内 Between 3-6 months"
 4 "6-12个月内 Between 6-12 months"
 5 "12个月以后 In 12 months or later"
 98 "还不确定 Not sure yet"
/Q5d_1 to Q5d_8
 1 "Ferris Wheel 摩天轮"
 2 "Carousel  旋转木马"
 3 "Soaring 翱翔?飞越地平线"
 4 "Mine Train 七个小矮人矿山车"
 5 "Tron 创极速光轮"
 6 "Pirates 加勒比海盗沉落宝藏之战"
 99 "Others 其他 （固定在倒数第二）"
 98 "None of above 以上均无（排他）"
/NEWS1_1 to NEWS1_6
 1 "New area (Disney.Pixels Toy Story) will open before summer 2018 新园区（迪士尼?皮克斯玩具总动园）将于2018年夏季前开幕"
 2 "New SS Pass is on sale in March 新一季春夏季卡3月发售"
 3 "New pricing will be applied in June 2018 2018年6月初将实行新的票价"
 4 "Half-price campaign on 8th March 3月8日的半价活动"
 5 "Spring campaign 春季的主题活动"
 98 "None of above 都不知道 (排他)"
/GENDER
 1 "Male 男性"
 2 "Female 女性"
/INCOME
 1 "Lower than RMB 5,000 人民币5,000元以下"
 2 "RMB 5,000 to 7,999 人民币5,000-7,999"
 3 "RMB 8,000 to 9,999 人民币8,000-9,999"
 4 "RMB 10,000 to 11,999 人民币10,000-11,999"
 5 "RMB 12,000 to 14,999 人民币12,000-14,999"
 6 "RMB 15,000 -15999 人民币 15,000-15,999"
 7 "RMB 16,000-19,999 人民币16,000-19,999"
 8 "RMB 20,000-24,999 人民币20,000-24,999"
 9 "RMB 25,000 and above 人民币25,000 或以上"
/LOCALRES
 1 "More than two years 两年以上"
 2 "One to two years   一到两年   "
 3 "Less than one year一年以下   "
/QMSTA
 1 "Single单身"
 2 "Married with kids已婚 – 有孩子"
 3 "Married no kids已婚– 没孩子"
 4 "Divorced / Separated with kids离婚 / 分居– 有孩子"
 5 "Divorced / Separated no kids离婚 / 分居 -没孩子"
 6 "Widowed with kids丧偶– 有孩子"
 7 "Widowed no kids丧偶 -没孩子"
.
EXECUTE.
